### ISSUE TITLE
Doesn't work :(

### ISSUE THREAD

**Issue by TheFlyingDog42** [CarelessInternet/node-schoolsoft#176]
I have tried for hours to get this to work, but all I get when I run the scrpit is an empty output. No errrors, nothing. Could you update the wiki so there is a way to troubleshoot on my own?

**Comment by CarelessInternet** [comment]
Everything still works for me. It's probably your initialization code where you construct the class. Is everything correct, including the school's name? Remember, the school name is the part after "sms.schoolsoft.se/"

![image](https://user-images.githubusercontent.com/59174259/187276953-1f714587-79c2-472b-9983-8d0c2f0a58bf.png)

If you are using this in the browser, I'm also experiencing problems because of axios. Don't use it in the browser until version 2 releases eventually.

Check the [testing file](https://github.com/CarelessInternet/node-schoolsoft/blob/ed9f69dacbd9c7f595f4218879256a5b53cd06a1/src/__tests__/index.test.js) if you haven't already for an example of how to use this package.

If you still can't get it to work, respond with as much information as you can about your code.

**Comment by TheFlyingDog42** [comment]
I haven't had time to test as much today, but I got the test version working. I just wanted to say that you should make a (somwhat coherent) guide on the wiki page, because trying to make sence of what everything does was quite difficult (because I suck but that's besides the point).
